In [7]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timezone, timedelta
import requests
from datetime import datetime
from restricted import key

# Text Sentiment analysis
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

In [10]:
def trading_yfin_2(ticker_symbol, start_date, end_date):
  start_date_ = datetime.strptime(start_date, '%Y-%m-%d')
  end_date_ = datetime.strptime(end_date, '%Y-%m-%d')
  ticker = yf.Ticker(ticker_symbol)
  data = ticker.history(start=start_date_, end=end_date_)
  #data.to_csv('lol.csv')
  return data

In [12]:
df = trading_yfin_2('AAPL', '2020-01-01', '2025-05-31')

In [14]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,71.344062,72.394093,71.091191,72.333885,135480400,0.0,0.0
2020-01-03 00:00:00-05:00,71.563213,72.389265,71.406674,71.630646,146322800,0.0,0.0
2020-01-06 00:00:00-05:00,70.754006,72.239935,70.503539,72.201401,118387200,0.0,0.0
2020-01-07 00:00:00-05:00,72.211049,72.466330,71.642689,71.861847,108872000,0.0,0.0
2020-01-08 00:00:00-05:00,71.565629,73.318885,71.565629,73.017845,132079200,0.0,0.0

In [15]:
import yfinance as yf

dat = yf.Ticker("MSFT")

# get historical market data
dat.history(period='1mo')

# options
dat.option_chain(dat.options[0]).calls

# get financials
dat.balance_sheet
dat.quarterly_income_stmt

# dates
dat.calendar

# general info
dat.info

# analysis
dat.analyst_price_targets

# websocket
dat.live()

Connected to WebSocket.
Subscribed to symbols: ['MSFT']
Listening for messages...
Received keyboard interrupt.
WebSocket connection closed.

In [77]:
gmt_plus_2 = timezone(timedelta(hours=2))

dat = yf.Search("AAPL")
all_news = dat.news

df_news = pd.DataFrame()

nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()

for i in range(len(all_news)):
    news_ = []
    news_.append(all_news[i]['title'])
    news_.append(all_news[i]['publisher'])
    news_.append(all_news[i]['link'])
    news_.append(datetime.fromtimestamp(all_news[i]['providerPublishTime'], tz=gmt_plus_2).strftime('%Y-%m-%d'))
    news_.append(all_news[i]['relatedTickers'])
    # concating news to df
    df_news = pd.concat([df_news, pd.DataFrame([news_], columns=['Title', 'Publisher', 'Link', 'Publication Date','Releated Tickets'])], ignore_index=True)

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/daniel_mac/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [92]:
dat = yf.Ticker('AAPL')
df = dat.quarterly_income_stmt.loc[["Total Revenue", "Gross Profit", "Operating Income", "EBITDA", "Net Income", "Diluted EPS", "Diluted Average Shares", "Cost Of Revenue", "Operating Expense"],:]#, "Interest Expense"],:]
for col in df.columns:
    col = str(col).split(' ')[0]
    df[col] = df[col].map('{:,.1f}'.format)

In [93]:
df

,2026-06-30,2026-03-31,2025-12-31,2025-09-30,2025-06-30
Total Revenue,"109,417,000,000.0","111,184,000,000.0","143,756,000,000.0","102,466,000,000.0","94,036,000,000.0"
Gross Profit,"54,770,000,000.0","54,781,000,000.0","69,231,000,000.0","48,341,000,000.0","43,718,000,000.0"
Operating Income,"35,695,000,000.0","35,885,000,000.0","50,852,000,000.0","32,427,000,000.0","28,202,000,000.0"
EBITDA,"39,015,000,000.0","39,324,000,000.0","54,066,000,000.0","35,554,000,000.0","31,032,000,000.0"
Net Income,"29,789,000,000.0","29,578,000,000.0","42,097,000,000.0","27,466,000,000.0","23,434,000,000.0"
Diluted EPS,2.0,2.0,2.8,1.9,1.6
Diluted Average Shares,"14,714,676,000.0","14,725,873,000.0","14,810,356,000.0","14,863,609,000.0","14,948,179,000.0"
Cost Of Revenue,"54,647,000,000.0","56,403,000,000.0","74,525,000,000.0","54,125,000,000.0","50,318,000,000.0"
Operating Expense,"19,075,000,000.0","18,896,000,000.0","18,379,000,000.0","15,914,000,000.0","15,516,000,000.0"

In [89]:
df

,2026-06-30,2026-03-31,2025-12-31,2025-09-30,2025-06-30
Total Revenue,"109,417,000,000.0","111,184,000,000.0","143,756,000,000.0","102,466,000,000.0","94,036,000,000.0"
Gross Profit,"54,770,000,000.0","54,781,000,000.0","69,231,000,000.0","48,341,000,000.0","43,718,000,000.0"
Operating Income,"35,695,000,000.0","35,885,000,000.0","50,852,000,000.0","32,427,000,000.0","28,202,000,000.0"
EBITDA,"39,015,000,000.0","39,324,000,000.0","54,066,000,000.0","35,554,000,000.0","31,032,000,000.0"
Net Income,"29,789,000,000.0","29,578,000,000.0","42,097,000,000.0","27,466,000,000.0","23,434,000,000.0"
Diluted EPS,2.0,2.0,2.8,1.9,1.6
Diluted Average Shares,"14,714,676,000.0","14,725,873,000.0","14,810,356,000.0","14,863,609,000.0","14,948,179,000.0"
Cost Of Revenue,"54,647,000,000.0","56,403,000,000.0","74,525,000,000.0","54,125,000,000.0","50,318,000,000.0"
Operating Expense,"19,075,000,000.0","18,896,000,000.0","18,379,000,000.0","15,914,000,000.0","15,516,000,000.0"

In [69]:
datetime.fromtimestamp(all_news[2]['providerPublishTime'], tz=gmt_plus_2).strftime('%Y-%m-%d')

'2026-10-02'

In [17]:
pip install --upgrade yfinance

Requirement already satisfied: yfinance in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (0.2.65)
Collecting yfinance
  Downloading yfinance-1.7.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.3-cp310-abi3-macosx_10_9_x86_64.whl.metadata (17 kB)
Collecting lxml>=4.9.0 (from yfinance)
  Downloading lxml-6.1.3-cp312-cp312-macosx_10_13_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: multitasking>=0.0.7 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: numpy>=1.16.5 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (2.3.1)
Requirement already satisfied: pandas>=1.3.0 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (2.3.0)
Requirement already satisfied: peewee>=3.16.2 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (3.18.2)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (4.3.8)
Requirement already satisfied: protobuf>=3.19.0 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (6.32.1)
Requirement already satisfied: pytz>=2022.5 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (2025.2)
Requirement already satisfied: requests>=2.31 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (2.32.4)
Requirement already satisfied: websockets>=13.0 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.14.0)
Collecting cffi>=2.0.0 (from curl_cffi>=0.15->yfinance)
  Downloading cffi-2.1.1-cp312-cp312-macosx_10_15_x86_64.whl.metadata (2.5 kB)
Requirement already satisfied: certifi>=2024.2.2 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2025.6.15)
Requirement already satisfied: pycparser in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/daniel_mac/anaconda3/envs/treffly/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.5.0)
Downloading yfinance-1.7.0-py3-none-any.whl (149 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-macosx_10_9_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 4.9 MB/s eta 0:00:00a 0:00:01
Downloading cffi-2.1.1-cp312-cp312-macosx_10_15_x86_64.whl (184 kB)
Downloading lxml-6.1.3-cp312-cp312-macosx_10_13_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 6.0 MB/s eta 0:00:00a 0:00:01
Installing collected packages: lxml, cffi, curl_cffi, yfinance
  Attempting uninstall: cffi━━━━━━━━━━━━━━━━━━━━ 0/4 [lxml]
    Found existing installation: cffi 1.17.1 0/4 [lxml]
    Uninstalling cffi-1.17.1:[0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/4 [cffi]
      Successfully uninstalled cffi-1.17.1━━━━━━━━━━━━━━━━━━━━━━━━ 1/4 [cffi]
  Attempting uninstall: curl_cffi━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/4 [cffi]
    Found existing installation: curl_cffi 0.13.0━━━━━━━━━━━━━ 1/4 [cffi]
    Uninstalling curl_cffi-0.13.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/4 [cffi]
      Successfully uninstalled curl_cffi-0.13.0━━━━━━━━━━━━━━━ 1/4 [cffi]
  Attempting uninstall: yfinance╺━━━━━━━━━━━━━━━━━━━ 2/4 [curl_cffi]
    Found existing installation: yfinance 0.2.65━━━━━━━━━━━━━━ 2/4 [curl_cffi]
    Uninstalling yfinance-0.2.65:╺━━━━━━━━━━━━━━━━━━━ 2/4 [curl_cffi]
      Successfully uninstalled yfinance-0.2.65━━━━━━━━━━━━━━━━ 2/4 [curl_cffi]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [yfinance]3/4 [yfinance]
Successfully installed cffi-2.1.1 curl_cffi-0.16.3 lxml-6.1.3 yfinance-1.7.0
Note: you may need to restart the kernel to use updated packages.

In [85]:
from fake_useragent import UserAgent

BASE_URL = "https://production.dataviz.cnn.io/index/fearandgreed/graphdata/"
START_DATE = datetime.today().strftime('%Y-%m-%d')
ua = UserAgent()

headers = {
   'User-Agent': ua.random,
   }

r = requests.get(BASE_URL + START_DATE, headers = headers)
data = r.json()

In [88]:
data['fear_and_greed']['score']

59.1714285714286

{'fear_and_greed': {'score': 59.1714285714286,
  'rating': 'greed',
  'timestamp': '2026-06-01T12:28:31+00:00',
  'previous_close': 60.1714285714286,
  'previous_1_week': 58.9714285714286,
  'previous_1_month': 71.17142857142856,
  'previous_1_year': 61.91428571428571},
 'fear_and_greed_historical': {'timestamp': 1780316911000.0,
  'score': 59.1714285714286,
  'rating': 'greed',
  'data': [{'x': 1780316911000.0, 'y': 59.1714285714286, 'rating': 'greed'}]},
 'market_momentum_sp500': {'timestamp': 1780088617000.0,
  'score': 98.2,
  'rating': 'extreme greed',
  'data': [{'x': 1780088617000.0, 'y': 7580.06, 'rating': 'extreme greed'}]},
 'market_momentum_sp125': {'timestamp': 1780088617000.0,
  'score': 98.2,
  'rating': 'extreme greed',
  'data': [{'x': 1780088617000.0,
    'y': 6944.52648,
    'rating': 'extreme greed'}]},
 'stock_price_strength': {'timestamp': 1780099194000.0,
  'score': 39.4,
  'rating': 'fear',
  'data': [{'x': 1780099194000.0,
    'y': 2.11282297283516,
    'rating': 'extreme fear'}]},
 'stock_price_breadth': {'timestamp': 1780099194000.0,
  'score': 33.4,
  'rating': 'fear',
  'data': [{'x': 1780099194000.0,
    'y': 1050.7182875358,
    'rating': 'extreme greed'}]},
 'put_call_options': {'timestamp': 1780086182000.0,
  'score': 97.8,
  'rating': 'extreme greed',
  'data': [{'x': 1780086182000.0,
    'y': 0.589403687443299,
    'rating': 'extreme fear'}]},
 'market_volatility_vix': {'timestamp': 1780316911000.0,
  'score': 50,
  'rating': 'neutral',
  'data': [{'x': 1780316911000.0, 'y': 15.83, 'rating': 'extreme fear'}]},
 'market_volatility_vix_50': {'timestamp': 1780316911000.0,
  'score': 50,
  'rating': 'neutral',
  'data': [{'x': 1780316911000.0, 'y': 19.9366, 'rating': 'extreme fear'}]},
 'junk_bond_demand': {'timestamp': 1780093800000.0,
  'score': 22.8,
  'rating': 'extreme fear',
  'data': [{'x': 1780093800000.0,
    'y': 1.3090120674258099,
    'rating': 'extreme fear'}]},
 'safe_haven_demand': {'timestamp': 1780084799000.0,
  'score': 79.6,
  'rating': 'extreme greed',
  'data': [{'x': 1780084799000.0,
    'y': 5.05674864205754,
    'rating': 'extreme fear'}]}}

In [123]:
import requests
url = "https://pro-api.coinmarketcap.com/v3/fear-and-greed/latest"
headers = {"X-CMC_PRO_API_KEY": key}
response = requests.get(url, headers=headers)
print(response.text)

{"data":{"value":31,"update_time":"2026-06-01T14:23:10.020Z","value_classification":"Fear"},"status":{"timestamp":"2026-06-01T14:24:05.920Z","error_code":"0","error_message":"","elapsed":1,"credit_count":1}}

In [126]:
a = response.json().get('data', [])

In [127]:
a.get('value')

31

In [132]:
a.get('update_time').split('T')[0]

'2026-06-01'

In [129]:
a.get('value_classification')

'Fear'