In [94]:
import yfinance as yf
import pandas as pd
from datetime import datetime
import requests
from datetime import datetime
from restricted import key

# Text Sentiment analysis
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

In [10]:
def trading_yfin_2(ticker_symbol, start_date, end_date):
  start_date_ = datetime.strptime(start_date, '%Y-%m-%d')
  end_date_ = datetime.strptime(end_date, '%Y-%m-%d')
  ticker = yf.Ticker(ticker_symbol)
  data = ticker.history(start=start_date_, end=end_date_)
  #data.to_csv('lol.csv')
  return data

In [12]:
df = trading_yfin_2('AAPL', '2020-01-01', '2025-05-31')

In [14]:
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,71.344062,72.394093,71.091191,72.333885,135480400,0.0,0.0
2020-01-03 00:00:00-05:00,71.563213,72.389265,71.406674,71.630646,146322800,0.0,0.0
2020-01-06 00:00:00-05:00,70.754006,72.239935,70.503539,72.201401,118387200,0.0,0.0
2020-01-07 00:00:00-05:00,72.211049,72.466330,71.642689,71.861847,108872000,0.0,0.0
2020-01-08 00:00:00-05:00,71.565629,73.318885,71.565629,73.017845,132079200,0.0,0.0

In [15]:
import yfinance as yf

dat = yf.Ticker("MSFT")

# get historical market data
dat.history(period='1mo')

# options
dat.option_chain(dat.options[0]).calls

# get financials
dat.balance_sheet
dat.quarterly_income_stmt

# dates
dat.calendar

# general info
dat.info

# analysis
dat.analyst_price_targets

# websocket
dat.live()

Connected to WebSocket.
Subscribed to symbols: ['MSFT']
Listening for messages...
Received keyboard interrupt.
WebSocket connection closed.

In [69]:
all_news = dat.news

df_news = pd.DataFrame()

nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()

for i in range(len(all_news)):
    news_ = []
    news_.append(all_news[i]['content']['title'])
    #news_.append(a[i]['content']['provider']['disaplyName'])
    news_.append(all_news[i]['content']['canonicalUrl']['url'])
    news_.append(all_news[i]['content']['pubDate'].split('T')[0])
    news_.append(all_news[i]['content']['summary'])
    sentiment_score = sid.polarity_scores(all_news[i]['content']['summary'])
    news_.append(sentiment_score['compound'])
    # concating news to df
    df_news = pd.concat([df_news, pd.DataFrame([news_], columns=['Title', 'Link', 'Publication Date','Summary','Sentiment'])], ignore_index=True)
    df_news['Feedback'] = df_news['Sentiment'].apply(lambda x: 'good' if x> 0.0 else ('bad' if x < 0.0 else 'neutral'))

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/daniel_mac/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [70]:
df_news

,Title,Link,Publication Date,Summary,Sentiment,Feedback
0,Big Tech companies are screwing the average in...,https://finance.yahoo.com/markets/article/big-...,2026-05-31,Time for some stock splits!,0.0000,neutral
1,Why This Fund Sold $35 Million of Bristow Grou...,https://www.fool.com/coverage/filings/2026/05/...,2026-05-31,Bristow Group delivers aviation and mission-cr...,0.2732,good
2,Amazon joins Microsoft in sending shocking mes...,https://www.thestreet.com/technology/amazon-jo...,2026-05-31,"For the past two years, the message from Big T...",0.6983,good
3,AI Bubble Debate Gets Real as Chip Stocks Rall...,https://finance.yahoo.com/markets/stocks/artic...,2026-05-31,(Bloomberg) -- Chipmakers are by far the hotte...,-0.2960,bad
4,S&P 500 Dividend Yield Hits 1.08%. The Lowest ...,https://247wallst.com/personal-finance/2026/05...,2026-05-31,The S&P 500 dividend yield has fallen to 1.08%...,-0.4019,bad
5,AI is turning energy into the hottest business...,https://www.axios.com/2026/05/31/ai-energy-bus...,2026-05-31,The AI boom is pushing companies across the ec...,0.2732,good
6,Microsoft (MSFT) Is Up 7.6% After Revealing US...,https://finance.yahoo.com/markets/stocks/artic...,2026-05-31,"In recent weeks, Microsoft has expanded its AI...",0.4767,good
7,Micron Just Entered the Trillion-Dollar Club. ...,https://www.fool.com/investing/2026/05/31/micr...,2026-05-31,Micron joins players including Nvidia and Micr...,0.1593,good
8,Every Big Tech Company Is Solving AI the Same ...,https://www.fool.com/investing/2026/05/30/ever...,2026-05-30,GlobalFoundries is quietly building the optica...,-0.3818,bad
9,Datadog Share Value Has More Than Doubled As I...,https://www.fool.com/investing/2026/05/30/data...,2026-05-30,Datadog crossed $1 billion in quarterly revenu...,-0.1280,bad

In [85]:
from fake_useragent import UserAgent

BASE_URL = "https://production.dataviz.cnn.io/index/fearandgreed/graphdata/"
START_DATE = datetime.today().strftime('%Y-%m-%d')
ua = UserAgent()

headers = {
   'User-Agent': ua.random,
   }

r = requests.get(BASE_URL + START_DATE, headers = headers)
data = r.json()

In [88]:
data['fear_and_greed']['score']

59.1714285714286

In [89]:
data

{'fear_and_greed': {'score': 59.1714285714286,
  'rating': 'greed',
  'timestamp': '2026-06-01T12:28:31+00:00',
  'previous_close': 60.1714285714286,
  'previous_1_week': 58.9714285714286,
  'previous_1_month': 71.17142857142856,
  'previous_1_year': 61.91428571428571},
 'fear_and_greed_historical': {'timestamp': 1780316911000.0,
  'score': 59.1714285714286,
  'rating': 'greed',
  'data': [{'x': 1780316911000.0, 'y': 59.1714285714286, 'rating': 'greed'}]},
 'market_momentum_sp500': {'timestamp': 1780088617000.0,
  'score': 98.2,
  'rating': 'extreme greed',
  'data': [{'x': 1780088617000.0, 'y': 7580.06, 'rating': 'extreme greed'}]},
 'market_momentum_sp125': {'timestamp': 1780088617000.0,
  'score': 98.2,
  'rating': 'extreme greed',
  'data': [{'x': 1780088617000.0,
    'y': 6944.52648,
    'rating': 'extreme greed'}]},
 'stock_price_strength': {'timestamp': 1780099194000.0,
  'score': 39.4,
  'rating': 'fear',
  'data': [{'x': 1780099194000.0,
    'y': 2.11282297283516,
    'rating': 'extreme fear'}]},
 'stock_price_breadth': {'timestamp': 1780099194000.0,
  'score': 33.4,
  'rating': 'fear',
  'data': [{'x': 1780099194000.0,
    'y': 1050.7182875358,
    'rating': 'extreme greed'}]},
 'put_call_options': {'timestamp': 1780086182000.0,
  'score': 97.8,
  'rating': 'extreme greed',
  'data': [{'x': 1780086182000.0,
    'y': 0.589403687443299,
    'rating': 'extreme fear'}]},
 'market_volatility_vix': {'timestamp': 1780316911000.0,
  'score': 50,
  'rating': 'neutral',
  'data': [{'x': 1780316911000.0, 'y': 15.83, 'rating': 'extreme fear'}]},
 'market_volatility_vix_50': {'timestamp': 1780316911000.0,
  'score': 50,
  'rating': 'neutral',
  'data': [{'x': 1780316911000.0, 'y': 19.9366, 'rating': 'extreme fear'}]},
 'junk_bond_demand': {'timestamp': 1780093800000.0,
  'score': 22.8,
  'rating': 'extreme fear',
  'data': [{'x': 1780093800000.0,
    'y': 1.3090120674258099,
    'rating': 'extreme fear'}]},
 'safe_haven_demand': {'timestamp': 1780084799000.0,
  'score': 79.6,
  'rating': 'extreme greed',
  'data': [{'x': 1780084799000.0,
    'y': 5.05674864205754,
    'rating': 'extreme fear'}]}}

In [123]:
import requests
url = "https://pro-api.coinmarketcap.com/v3/fear-and-greed/latest"
headers = {"X-CMC_PRO_API_KEY": key}
response = requests.get(url, headers=headers)
print(response.text)

{"data":{"value":31,"update_time":"2026-06-01T14:23:10.020Z","value_classification":"Fear"},"status":{"timestamp":"2026-06-01T14:24:05.920Z","error_code":"0","error_message":"","elapsed":1,"credit_count":1}}

In [126]:
a = response.json().get('data', [])

In [127]:
a.get('value')

31

In [132]:
a.get('update_time').split('T')[0]

'2026-06-01'

In [129]:
a.get('value_classification')

'Fear'